apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-dev-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/olnytim/inception-of-things.git'
    targetRevision: 'main'
    path: 'p3/confs/dev'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
