Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    end

    # Master
    config.vm.define "tgalyautS" do |serv|
        serv.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
        serv.vm.hostname = "tgalyautS"
        serv.vm.network "private_network", ip: "192.168.56.110"
        serv.vm.post_up_message = "To connect to virtual machine use 'vagrant ssh tgalyautS'"
        serv.vm.provider "virtualbox" do |first|
            first.name = "master"
        end
        serv.vm.provision "shell", path: "./scripts/master.sh"
    end

    # Worker
    config.vm.define "tgalyautSW" do |serv|
        serv.vm.synced_folder "./confs", "/vagrant", type:"virtualbox"
        serv.vm.hostname = "tgalyautSW"
        serv.vm.network "private_network", ip: "192.168.56.111"
        serv.vm.post_up_message = "To connect to virtual machine use 'vagrant ssh tgalyautSW'"
        serv.vm.provider "virtualbox" do |first|
            first.name = "worker"
        end
        serv.vm.provision "shell", path: "./scripts/worker.sh"
    end
end
