apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil
  namespace: dev
  labels:
    app: wil
spec:
  selector:
    matchLabels:
      app: wil
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
        - name: wil
          image: ckaserer/hello-kubernetes:latest #wil42/playground:v2 #
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "Hello from App1"
